# permissions for end users to edit pets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: pet-controller
    app.kubernetes.io/managed-by: kustomize
  name: pet-editor-role
rules:
- apiGroups:
  - linuxfest.example.com
  resources:
  - pets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - linuxfest.example.com
  resources:
  - pets/status
  verbs:
  - get
