apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pets.animals.example.com
spec:
  group: animals.example.com
  names:
    kind: Pet
    plural: pets
    singular: pet
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                food:
                  type: integer
                love:
                  type: integer
